# Generated by Django 4.2 on 2023-05-09 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0003_alter_dailycalorietarget_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterintake',
            old_name='custom_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='waterintake',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='waterintake',
            unique_together={('user', 'date')},
        ),
    ]
