# Generated by Django 4.2 on 2023-05-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0005_alter_waterintake_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterIntake',
        ),
    ]
