# Generated by Django 4.2 on 2023-05-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0007_waterintake'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('user', 'date_added')},
        ),
    ]
