# Generated by Django 4.2 on 2023-05-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0008_alter_fooditem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailycalorietarget',
            unique_together={('user', 'date_added')},
        ),
    ]
