# Generated by Django 4.2 on 2023-05-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0011_alter_dailycalorietarget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycalorietarget',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
